name: '游댧 Tarefa de Pesquisa / Prova de Conceito (PoC)'
description: 'Utilize este modelo para tarefas de pesquisa de ferramentas ou valida칞칚o de conceitos.'
title: "[PESQUISA]: "
labels: ["research", "PoC"]
projects: ["sua-org/numero-do-projeto"]
assignees: []
body:
  - type: textarea
    id: objective
    attributes:
      label: Pergunta a ser Respondida / Objetivo
      description: Qual 칠 o objetivo principal desta pesquisa? O que queremos descobrir ou validar?
      placeholder: "Ex: Avaliar se a ferramenta 'Echidna' 칠 eficaz para encontrar vulnerabilidades de 'integer overflow' em nossos contratos de exemplo."
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Escopo da Pesquisa
      description: Defina claramente o que ser치 (e o que N츾O ser치) investigado.
      placeholder: |
        **No escopo:**
        - Instala칞칚o e configura칞칚o da ferramenta.
        - Execu칞칚o contra 2 contratos de teste.
        - An치lise da facilidade de uso e qualidade dos relat칩rios.

        **Fora do escopo:**
        - An치lise de performance em larga escala.
        - Integra칞칚o com o pipeline de CI/CD.
    validations:
      required: true
  - type: textarea
    id: deliverables
    attributes:
      label: Entreg치veis Esperados
      description: Qual ser치 o resultado final desta tarefa? Use checkboxes (`- [ ]`).
      placeholder: |
        - [ ] Um documento de decis칚o na Wiki com pr칩s e contras.
        - [ ] Um reposit칩rio de exemplo com a PoC funcional.
    validations:
      required: true